language: node_js

node_js: "node"

os:
  - linux
  - osx
  - windows

matrix:
  include:
    - node_js: "6"
  allow_failures:
    - os: osx
    - os: windows
  fast_finish: true

before_install: |
  if [ "${TRAVIS_OS_NAME}" = 'windows' ]; then
    npm config set script-shell 'bash'
  fi

script: |
  if [ "${TRAVIS_OS_NAME}" = 'linux' ]; then
    xvfb-run npm run test:full
  else
    npm run test:full
  fi
